"""
Django settings for gotta_bike project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import datetime
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# EXTERNAL_CONFIG_PATH = '/opt/webapps/gotta_bike/etc/external_config.py'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '<RACE_MEMBERSHIP_SECRET_KEY>'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'bootstrap_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    #allauth-apps
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    #end-allauth-apps
    'dbbackup',
    'bootstrap3',
    'bootstrap4',
    'django_filters',
    'storages',
    'rest_framework',
    'rest_framework_tracking',
    'phonenumber_field',
    'reversion',
    'corsheaders',
    'anymail',
    'dynamic_preferences',
    'ckeditor',
    'apps.administration',
    'apps.shop',
]

MIDDLEWARE = [
    'service_bond.helpers.middleware.SubpathURLRoutingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'service_bond.helpers.middleware.DisableCSRFMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'service_bond.helpers.middleware.InjectUiVersionInHeadersMiddleware',
    'service_bond.helpers.middleware.CustomRevisionMiddleware',
]

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'service_bond.helpers.utils.custom_rest_exception_handler',
    'DEFAULT_PERMISSION_CLASSES': [
        'service_bond.helpers.utils.CustomDjangoModelPermissions'
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1'],
    'VERSION_PARAM': 'version',

    'PAGE_SIZE': 25,
    'MAX_PAGE_SIZE_DEFAULT': 200,
    'ORDERING_PARAM': 'order_by',
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_PAGINATION_CLASS': 'service_bond.helpers.utils.CustomPagination',
    'DEFAULT_FILTER_BACKENDS': (
                                'rest_framework.filters.SearchFilter',
                                'service_bond.helpers.utils.ExtendedOrderingFilterBackend'),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
}

JWT_AUTH = {
    'JWT_ENCODE_HANDLER': 'rest_framework_jwt.utils.jwt_encode_handler',
    'JWT_DECODE_HANDLER': 'rest_framework_jwt.utils.jwt_decode_handler',
    'JWT_PAYLOAD_HANDLER': 'rest_framework_jwt.utils.jwt_payload_handler',
    'JWT_PAYLOAD_GET_USER_ID_HANDLER': 'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'rest_framework_jwt.utils.jwt_response_payload_handler',
    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=36000),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,
    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_AUTH_HEADER_PREFIX': 'Consensus',
}

ROOT_URLCONF = 'service_bond.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'service_bond', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'dynamic_preferences.processors.global_preferences',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
            ],
            # 'libraries': {
            #     'util_tags': 'gotta_bike.templatetags.util_tags',
            # }
        },
    },
]

WSGI_APPLICATION = 'service_bond.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CSRF_DISABLED = False  # disable checking csrf. warning!!! this should be set to False in production

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB

PHONENUMBER_DB_FORMAT = 'RFC3966'

# Custom Django auth settings

AUTH_USER_MODEL = 'administration.User'
AUTHENTICATION_BACKENDS = [
    'service_bond.helpers.utils.shopModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/ui-panel'

SITE_ID = 1


DEFAULT_FILE_STORAGE = 'service_bond.helpers.utils.OverwriteFileSystemStorage'
PUBLIC_FILE_STORAGE = 'service_bond.helpers.utils.OverwriteFileSystemStorage'

# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "collected_static")

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s %(pathname)s:%(lineno)d %(message)s'
        },
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}

SUBPATH_URLCONFS = {
    # None: 'service_bond.urls',
    'shop': 'service_bond.urls_shop',
}




# drf_tracking settings
DRF_TRACKING_LOGGING_METHODS = ['POST', 'PUT', 'PATCH', 'DELETE']
DRF_TRACKING_SKIP_RESPONSE_DATA = {'get': True, 'option': True, 'head': True}
DRF_TRACKING_SKIP_REQUEST_DATA = False
DRF_TRACKING_SKIP_REQUEST_QUERY_PARAMS = False
DRF_TRACKING_SKIP_ERRORS_DATA = False


# project specific settings
SIGNUP_REQUEST_PUBLIC_DISABLED = False
SIGNUP_ACTIVATION_SALT = 'signup-activation'
SIGNUP_ACTIVATION_AGE = 24 * 3600  # 1 day
RECOVERY_PASSWORD_SALT = 'recovery-password'
RECOVERY_PASSWORD_AGE = 3600  # 1 hour
PAGINATION_DEFAULT_PAGINATION = 15
PAGINATION_MAX_SIZE = 200
