# Generated by Django 3.1.4 on 2021-01-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210124_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
